server:
  port: 8081
spring:
  profiles:
    active: native
  application:
    name: microservice-config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-data