server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  mail:
    host: smtp.gmail.com
    # ... (resto de la configuración de mail)
  application:
    name: microservice-manager

---
# INICIO DE LA CONFIGURACIÓN ESPECÍFICA PARA EL PERFIL 'docker'

spring: # <-- Esta es la clave principal 'spring'
  config:
    activate:
      on-profile: docker # <-- Activa el perfil
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/microservice_manager?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

eureka: # <-- Esta es la clave principal 'eureka'
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://discovery-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}