server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://host.docker.internal:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: microservice-manager
            uri: lb://microservice-manager
            predicates:
              - Path=/api/managers/**
          - id: microservice-news
            uri: lb://microservice-news
            predicates:
              - Path=/api/news/**
          - id: microservice-project
            uri: lb://microservice-project
            predicates:
              - Path=/api/projects/**
          - id: microservice-voluntary
            uri: lb://microservice-voluntary
            predicates:
              - Path=/api/voluntaries/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

