server:
  port: 8761
spring:
  application:
    name: microservice-discovery-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    server-url:
      defaultZone: http://host.docker.internal:${server.port}/eureka/