version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_manager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  config-service:
    build: ./microservice-config-service
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/8081' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  discovery-server:
    build: ./microservice-discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  api-gateway:
    build: ./microservice-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - discovery-server

  microservice-manager:
    build: ./microservice-manager
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      config-service:
        condition: service_healthy
      api-gateway:
        condition: service_started
      mysql:
        condition: service_started

  microservice-voluntary:
    build: ./microservice-voluntary
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      config-service:
        condition: service_healthy
      api-gateway:
        condition: service_started
      mysql:
        condition: service_started

  microservice-project:
    build: ./microservice-project
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      config-service:
        condition: service_healthy
      api-gateway:
        condition: service_started
      mysql:
        condition: service_started

  microservice-news:
    build: ./microservice-news
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      config-service:
        condition: service_healthy
      api-gateway:
        condition: service_started
      mysql:
        condition: service_started

volumes:
  mysql_data: