server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  mail:
    host: smtp.gmail.com
    #
    #
    # CAMBIAR ESTO PARA FEDERACION.MESASOLIDARIATANDIL@GMAIL.COM
    # RECORDAR SI NO FUNCIONA APAGAR EL ANTIVIRUS Y EL FIREWALL
    #
    username: lorenzofdzdev@gmail.com
    password: ghwu tgjb wrra iybn
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: microservice-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice_manager?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}